// Generated by Wrangler by running `wrangler types`

interface Env {
	UPSTASH_REDIS_REST_TOKEN: string;
	UPSTASH_REDIS_REST_URL: string;
	REDIRECT_CACHE_SECONDS: string;
	DB: D1Database;
	ASSETS: Fetcher;
}
