// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	AUTH_SECRET: string;
	AUTH_GITHUB_ID: string;
	AUTH_GITHUB_SECRET: string;
	DB: D1Database;
}
